version: '3.4'

services:
  tgprov4:
    image: ${DOCKER_REGISTRY-}tgprov4
    build:
      context: .
      dockerfile: src/TGProV4.Server/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=db;Database=tgprov4;User=sa;Password=P@ssw0rd1;MultipleActiveResultSets=true"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd1"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5002:5002"
      - "5003:5003"
    depends_on:
      - db
    restart: on-failure
    container_name: tgprov4

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=P@ssw0rd1"
      - "ACCEPT_EULA=Y"
    ports:
      - "1433:1433"
    container_name: mssql
