//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGProV4.Server.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServerCommonResources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerCommonResources_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGProV4.Server.Resources.Localization.ServerCommonResources.en", typeof(ServerCommonResources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent. Please check your mailbox and follow the instructions..
        /// </summary>
        internal static string An_email_has_been_sent__Please_check_your_mailbox_and_follow_the_instructions_ {
            get {
                return ResourceManager.GetString("An email has been sent. Please check your mailbox and follow the instructions.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while trying to upload an image..
        /// </summary>
        internal static string An_error_has_occurred_while_trying_to_upload_an_image_ {
            get {
                return ResourceManager.GetString("An error has occurred while trying to upload an image.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error has occurred..
        /// </summary>
        internal static string An_unhandled_error_has_occurred_ {
            get {
                return ResourceManager.GetString("An unhandled error has occurred.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not confirmed..
        /// </summary>
        internal static string Email_is_not_confirmed_ {
            get {
                return ResourceManager.GetString("Email is not confirmed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is incorrect..
        /// </summary>
        internal static string Email_or_password_is_incorrect_ {
            get {
                return ResourceManager.GetString("Email or password is incorrect.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Client Token..
        /// </summary>
        internal static string Invalid_Client_Token_ {
            get {
                return ResourceManager.GetString("Invalid Client Token.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more required header values were missing..
        /// </summary>
        internal static string One_or_more_required_header_values_were_missing_ {
            get {
                return ResourceManager.GetString("One or more required header values were missing.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation failures have occurred..
        /// </summary>
        internal static string One_or_more_validation_failures_have_occurred_ {
            get {
                return ResourceManager.GetString("One or more validation failures have occurred.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Has Been Expired..
        /// </summary>
        internal static string Token_Has_Been_Expired_ {
            get {
                return ResourceManager.GetString("Token Has Been Expired.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Has Been Revoked..
        /// </summary>
        internal static string Token_Has_Been_Revoked_ {
            get {
                return ResourceManager.GetString("Token Has Been Revoked.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to add or delete Administrator Role..
        /// </summary>
        internal static string You_are_not_allowed_to_add_or_delete_Administrator_Role_ {
            get {
                return ResourceManager.GetString("You are not allowed to add or delete Administrator Role.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized!.
        /// </summary>
        internal static string You_are_not_authorized_ {
            get {
                return ResourceManager.GetString("You are not authorized!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this resource!.
        /// </summary>
        internal static string You_are_not_authorized_to_access_this_resource_ {
            get {
                return ResourceManager.GetString("You are not authorized to access this resource!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked! Please contact your website administrator for more information..
        /// </summary>
        internal static string Your_account_has_been_locked__Please_contact_your_website_administrator_for_more_information_ {
            get {
                return ResourceManager.GetString("Your account has been locked! Please contact your website administrator for more " +
                        "information.", resourceCulture);
            }
        }
    }
}
